First stab at new world for zipl

diff --git a/util/zipl-s390.in b/util/zipl-s390.in
--- a/util/zipl-s390.in
+++ b/util/zipl-s390.in
@@ -15,6 +15,25 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #
+set -E
+set -e
 
+if [ -x /usr/libexec/grubby/functions ]; then
+    source /usr/libexec/grubby/functions
+else
+    echo "Could not import grubby library functions" 1>&2
+    exit 1
+fi
 
+CONFIG=/etc/zipl.conf
+checkarch s390
+checkcfg $CONFIG
+checkefi
+CONFIG=$(realpath $CONFIG)
 
+append_title()
+{
+	echo "$@" | sed 's/ /_/g'
+}
+
+main --configfile=$CONFIG --loader=--zipl "$@"
