fixed error redirection (76933)

diff --git a/grubby/new-kernel-pkg b/grubby/new-kernel-pkg
--- a/grubby/new-kernel-pkg
+++ b/grubby/new-kernel-pkg
@@ -127,7 +127,7 @@ mkinitrd() {
     /sbin/mkinitrd -f $initrdfile $version
     rc=$?
     if [ $rc != 0 ]; then
-	echo "mkinitrd failed" >2
+	echo "mkinitrd failed" >&2
 	exit 1
     fi
 }
